USE cs6400;

## User
INSERT INTO User VALUES ('a@123.com', 'pwd', 'Allen', 'Ruta', '2016-01-01', '2154786705');
INSERT INTO User VALUES ('b@123.com', 'pwd', 'Lucy', 'Boulter', '2017-12-25', '6656503829');
INSERT INTO User VALUES ('c@123.com', 'pwd', 'Chris', 'Boord', '2018-12-30', '1875176352');
INSERT INTO User VALUES ('admin@123.com', 'mo', 'David', 'Burdell', '2015-01-01', '7807479196');

# Owner
INSERT INTO Owner VALUES ('admin@123.com');

# Dog
INSERT INTO Dog VALUES (1, 'a@123.com', 'Katie', 'unknown', 1, 'Very well-behaved pup for her age. She is a happy, friendly girl.', 67, NULL, '2016-01-03', 'found as stray by animal control department', 1);
INSERT INTO Dog VALUES (2, 'b@123.com', 'Cash', 'male', 1, 'very friendly and playful', 121, '1722217411', '2016-07-03', "owner passed away", 0);
INSERT INTO Dog VALUES (3, 'c@123.com', 'Finn', 'male', 1, ' shy when meet new dogs', 63, '0332935780', '2019-01-08', 'found as stray by animal control department', 1);
INSERT INTO Dog VALUES (4, 'admin@123.com', 'Mimi', 'female', 1, 'Love long walks in the park and can be a couch pot', 25, '3359157588', '2019-01-14', 'Move out of country', 0);

# Breed
INSERT INTO Breed VALUES ('Affenpinscher');
INSERT INTO Breed VALUES ('Afghan Hound');
INSERT INTO Breed VALUES ('Airedale Terrier');
INSERT INTO Breed VALUES ('Akbash Dog');
INSERT INTO Breed VALUES ('Akita');
INSERT INTO Breed VALUES ('Alapaha Blue Blood Bulldog');
INSERT INTO Breed VALUES ('Alaskan Husky');
INSERT INTO Breed VALUES ('Alaskan Malamute');
INSERT INTO Breed VALUES ('American Bulldog');
INSERT INTO Breed VALUES ('American Eskimo');
INSERT INTO Breed VALUES ('American Foxhound');
INSERT INTO Breed VALUES ('American Pit Bull Terrier');
INSERT INTO Breed VALUES ('American Staffordshire Terrier');
INSERT INTO Breed VALUES ('American Water Spaniel');
INSERT INTO Breed VALUES ('Anatolian Shepherd Dog');
INSERT INTO Breed VALUES ('Aussiedoodle');
INSERT INTO Breed VALUES ('Australian Cattle Dog');
INSERT INTO Breed VALUES ('Australian Kelpie');
INSERT INTO Breed VALUES ('Australian Shepherd');
INSERT INTO Breed VALUES ('Australian Terrier');
INSERT INTO Breed VALUES ('Azawakh');
INSERT INTO Breed VALUES ('Basador');
INSERT INTO Breed VALUES ('Basenji');
INSERT INTO Breed VALUES ('Basset Bleu de Gascogne');
INSERT INTO Breed VALUES ('Basset Hound');
INSERT INTO Breed VALUES ('Beagle');
INSERT INTO Breed VALUES ('Bearded Collie');
INSERT INTO Breed VALUES ('Beauceron');
INSERT INTO Breed VALUES ('Bedlington Terrier');
INSERT INTO Breed VALUES ('Belgian Laekenois');
INSERT INTO Breed VALUES ('Belgian Malinois');
INSERT INTO Breed VALUES ('Belgian Sheepdog');
INSERT INTO Breed VALUES ('Belgian Tervuren');
INSERT INTO Breed VALUES ('Bergamasco');
INSERT INTO Breed VALUES ('Berger Picard');
INSERT INTO Breed VALUES ('Bernese Mountain Dog');
INSERT INTO Breed VALUES ('Bichon Frise');
INSERT INTO Breed VALUES ('Black and Tan Coonhound');
INSERT INTO Breed VALUES ('Black Russian Terrier');
INSERT INTO Breed VALUES ('Bloodhound');
INSERT INTO Breed VALUES ('Blue Picardy Spaniel');
INSERT INTO Breed VALUES ('Bluetick Coonhound');
INSERT INTO Breed VALUES ('Boerboel');
INSERT INTO Breed VALUES ('Bolognese');
INSERT INTO Breed VALUES ('Border Collie');
INSERT INTO Breed VALUES ('Border Terrier');
INSERT INTO Breed VALUES ('Borzoi');
INSERT INTO Breed VALUES ('Boston Terrier');
INSERT INTO Breed VALUES ('Bouvier des Flandres');
INSERT INTO Breed VALUES ('Boxer');
INSERT INTO Breed VALUES ('Boykin Spaniel');
INSERT INTO Breed VALUES ('Bracco Italiano');
INSERT INTO Breed VALUES ('Briard');
INSERT INTO Breed VALUES ('Brittany');
INSERT INTO Breed VALUES ('Brussels Griffon');
INSERT INTO Breed VALUES ('Bull Terrier');
INSERT INTO Breed VALUES ('Bulldog');
INSERT INTO Breed VALUES ('Bullmastiff');
INSERT INTO Breed VALUES ('Cairn Terrier');
INSERT INTO Breed VALUES ('Canaan Dog');
INSERT INTO Breed VALUES ('Cane Corso');
INSERT INTO Breed VALUES ('Cardigan Welsh Corgi');
INSERT INTO Breed VALUES ('Catahoula Leopard Dog');
INSERT INTO Breed VALUES ('Caucasian Ovcharka');
INSERT INTO Breed VALUES ('Cavalier King Charles Spaniel');
INSERT INTO Breed VALUES ('Cavapom');
INSERT INTO Breed VALUES ('Cavapoo');
INSERT INTO Breed VALUES ('Cesky Terrier');
INSERT INTO Breed VALUES ('Chart Polski');
INSERT INTO Breed VALUES ('Chesapeake Bay Retriever');
INSERT INTO Breed VALUES ('Chihuahua');
INSERT INTO Breed VALUES ('Chinese Crested');
INSERT INTO Breed VALUES ('Chinese Shar-Pei');
INSERT INTO Breed VALUES ('Chinook');
INSERT INTO Breed VALUES ('Chow Chow');
INSERT INTO Breed VALUES ('Chug');
INSERT INTO Breed VALUES ("Cirneco dell'Etna");
INSERT INTO Breed VALUES ('Clumber Spaniel');
INSERT INTO Breed VALUES ('Cockapoo');
INSERT INTO Breed VALUES ('Cocker Spaniel');
INSERT INTO Breed VALUES ('Collie');
INSERT INTO Breed VALUES ('Coton de Tulear');
INSERT INTO Breed VALUES ('Curly-Coated Retriever');
INSERT INTO Breed VALUES ('Dachshund');
INSERT INTO Breed VALUES ('Dalmatian');
INSERT INTO Breed VALUES ('Dandie Dinmont Terrier');
INSERT INTO Breed VALUES ('Doberman Pinscher');
INSERT INTO Breed VALUES ('Dogo Argentino');
INSERT INTO Breed VALUES ('Dogue de Bordeaux');
INSERT INTO Breed VALUES ('Doxiepoo');
INSERT INTO Breed VALUES ('English Cocker Spaniel');
INSERT INTO Breed VALUES ('English Foxhound');
INSERT INTO Breed VALUES ('English Setter');
INSERT INTO Breed VALUES ('English Springer Spaniel');
INSERT INTO Breed VALUES ('English Toy Spaniel');
INSERT INTO Breed VALUES ('Entlebucher Mountain Dog');
INSERT INTO Breed VALUES ('Eurasier');
INSERT INTO Breed VALUES ('Field Spaniel');
INSERT INTO Breed VALUES ('Fila Brasileiro');
INSERT INTO Breed VALUES ('Finnish Lapphund');
INSERT INTO Breed VALUES ('Finnish Spitz');
INSERT INTO Breed VALUES ('Flat-Coated Retriever');
INSERT INTO Breed VALUES ('Fox Terrier');
INSERT INTO Breed VALUES ('French Bulldog');
INSERT INTO Breed VALUES ('German Pinscher');
INSERT INTO Breed VALUES ('German Shepherd Dog');
INSERT INTO Breed VALUES ('German Shorthaired Pointer');
INSERT INTO Breed VALUES ('German Spitz');
INSERT INTO Breed VALUES ('German Wirehaired Pointer');
INSERT INTO Breed VALUES ('Giant Schnauzer');
INSERT INTO Breed VALUES ('Glen of Imaal Terrier');
INSERT INTO Breed VALUES ('Golden Retriever');
INSERT INTO Breed VALUES ('Goldendoodle');
INSERT INTO Breed VALUES ('Gordon Setter');
INSERT INTO Breed VALUES ('Great Dane');
INSERT INTO Breed VALUES ('Great Pyrenees');
INSERT INTO Breed VALUES ('Greater Swiss Mountain Dog');
INSERT INTO Breed VALUES ('Greyhound');
INSERT INTO Breed VALUES ('Harrier');
INSERT INTO Breed VALUES ('Havanese');
INSERT INTO Breed VALUES ('Ibizan Hound');
INSERT INTO Breed VALUES ('Icelandic Sheepdog');
INSERT INTO Breed VALUES ('Irish Red and White Setter');
INSERT INTO Breed VALUES ('Irish Setter');
INSERT INTO Breed VALUES ('Irish Terrier');
INSERT INTO Breed VALUES ('Irish Water Spaniel');
INSERT INTO Breed VALUES ('Irish Wolfhound');
INSERT INTO Breed VALUES ('Italian Greyhound');
INSERT INTO Breed VALUES ('Jack Russell Terrier');
INSERT INTO Breed VALUES ('Japanese Chin');
INSERT INTO Breed VALUES ('Keeshond');
INSERT INTO Breed VALUES ('Kerry Blue Terrier');
INSERT INTO Breed VALUES ('Komondor');
INSERT INTO Breed VALUES ('Kooikerhondje');
INSERT INTO Breed VALUES ('Kromfohrlander');
INSERT INTO Breed VALUES ('Kuvasz');
INSERT INTO Breed VALUES ('Labradoodle');
INSERT INTO Breed VALUES ('Labrador Retriever');
INSERT INTO Breed VALUES ('Lacy Dog');
INSERT INTO Breed VALUES ('Lagotto Romagnolo');
INSERT INTO Breed VALUES ('Lakeland Terrier');
INSERT INTO Breed VALUES ('Large Munsterlander');
INSERT INTO Breed VALUES ('Leonberger');
INSERT INTO Breed VALUES ('Lhasa Apso');
INSERT INTO Breed VALUES ('Lhasapoo');
INSERT INTO Breed VALUES ('Longdog');
INSERT INTO Breed VALUES ('Lowchen');
INSERT INTO Breed VALUES ('Lurcher');
INSERT INTO Breed VALUES ('Maltese');
INSERT INTO Breed VALUES ('Maltipoo');
INSERT INTO Breed VALUES ('Manchester Terrier');
INSERT INTO Breed VALUES ('Mastiff');
INSERT INTO Breed VALUES ('Miniature American Shepherd');
INSERT INTO Breed VALUES ('Miniature Bull Terrier');
INSERT INTO Breed VALUES ('Miniature Pinscher');
INSERT INTO Breed VALUES ('Miniature Schnauzer');
INSERT INTO Breed VALUES ('Mixed');
INSERT INTO Breed VALUES ('Mudi');
INSERT INTO Breed VALUES ('Neapolitan Mastiff');
INSERT INTO Breed VALUES ('Newfoundland');
INSERT INTO Breed VALUES ('Norfolk Terrier');
INSERT INTO Breed VALUES ('Norwegian Buhund');
INSERT INTO Breed VALUES ('Norwegian Elkhound');
INSERT INTO Breed VALUES ('Norwegian Lundehund');
INSERT INTO Breed VALUES ('Norwich Terrier');
INSERT INTO Breed VALUES ('Nova Scotia Duck Tolling Retriever');
INSERT INTO Breed VALUES ('Old English Sheepdog');
INSERT INTO Breed VALUES ('Otterhound');
INSERT INTO Breed VALUES ('Papillon');
INSERT INTO Breed VALUES ('Pekeapoo');
INSERT INTO Breed VALUES ('Pekingese');
INSERT INTO Breed VALUES ('Pembroke Welsh Corgi');
INSERT INTO Breed VALUES ('Perro de Presa Canario');
INSERT INTO Breed VALUES ('Peruvian Inca Orchid');
INSERT INTO Breed VALUES ('Petit Basset Griffon Vendeen');
INSERT INTO Breed VALUES ('Pharaoh Hound');
INSERT INTO Breed VALUES ('Plott');
INSERT INTO Breed VALUES ('Pointer');
INSERT INTO Breed VALUES ('Polish Lowland Sheepdog');
INSERT INTO Breed VALUES ('Pomapoo');
INSERT INTO Breed VALUES ('Pomeranian');
INSERT INTO Breed VALUES ('Pomsky');
INSERT INTO Breed VALUES ('Poodle');
INSERT INTO Breed VALUES ('Portuguese Podengo');
INSERT INTO Breed VALUES ('Portuguese Water Dog');
INSERT INTO Breed VALUES ('Pug');
INSERT INTO Breed VALUES ('Pugapoo');
INSERT INTO Breed VALUES ('Puggle');
INSERT INTO Breed VALUES ('Puli');
INSERT INTO Breed VALUES ('Pumi');
INSERT INTO Breed VALUES ('Pyrenean Shepherd');
INSERT INTO Breed VALUES ('Rat Terrier');
INSERT INTO Breed VALUES ('Redbone Coonhound');
INSERT INTO Breed VALUES ('Rhodesian Ridgeback');
INSERT INTO Breed VALUES ('Rottweiler');
INSERT INTO Breed VALUES ('Russian Toy');
INSERT INTO Breed VALUES ('Saint Bernard');
INSERT INTO Breed VALUES ('Saluki');
INSERT INTO Breed VALUES ('Samoyed');
INSERT INTO Breed VALUES ('Schapendoes');
INSERT INTO Breed VALUES ('Schipperke');
INSERT INTO Breed VALUES ('Schnoodle');
INSERT INTO Breed VALUES ('Scottish Deerhound');
INSERT INTO Breed VALUES ('Scottish Terrier');
INSERT INTO Breed VALUES ('Sealyham Terrier');
INSERT INTO Breed VALUES ('Shetland Sheepdog');
INSERT INTO Breed VALUES ('Shiba Inu');
INSERT INTO Breed VALUES ('Shih Tzu');
INSERT INTO Breed VALUES ('Shihpoo');
INSERT INTO Breed VALUES ('Siberian Husky');
INSERT INTO Breed VALUES ('Silken Windhound');
INSERT INTO Breed VALUES ('Silky Terrier');
INSERT INTO Breed VALUES ('Skye Terrier');
INSERT INTO Breed VALUES ('Sloughi');
INSERT INTO Breed VALUES ('Small Munsterlander Pointer');
INSERT INTO Breed VALUES ('Soft Coated Wheaten Terrier');
INSERT INTO Breed VALUES ('Spanish Greyhound');
INSERT INTO Breed VALUES ('Spanish Water Dog');
INSERT INTO Breed VALUES ('Spinone Italiano');
INSERT INTO Breed VALUES ('Sprollie');
INSERT INTO Breed VALUES ('Staffordshire Bull Terrier');
INSERT INTO Breed VALUES ('Standard Schnauzer');
INSERT INTO Breed VALUES ('Sussex Spaniel');
INSERT INTO Breed VALUES ('Swedish Lapphund');
INSERT INTO Breed VALUES ('Swedish Vallhund');
INSERT INTO Breed VALUES ('Thai Ridgeback');
INSERT INTO Breed VALUES ('Tibetan Mastiff');
INSERT INTO Breed VALUES ('Tibetan Spaniel');
INSERT INTO Breed VALUES ('Tibetan Terrier');
INSERT INTO Breed VALUES ('Tosa Ken');
INSERT INTO Breed VALUES ('Toy Fox Terrier');
INSERT INTO Breed VALUES ('Toy Poodle');
INSERT INTO Breed VALUES ('Treeing Walker Coonhound');
INSERT INTO Breed VALUES ('Unknown');
INSERT INTO Breed VALUES ('Vizsla');
INSERT INTO Breed VALUES ('Volpino Italiano');
INSERT INTO Breed VALUES ('Weimaraner');
INSERT INTO Breed VALUES ('Welsh Springer Spaniel');
INSERT INTO Breed VALUES ('Welsh Terrier');
INSERT INTO Breed VALUES ('West Highland White Terrier');
INSERT INTO Breed VALUES ('Whippet');
INSERT INTO Breed VALUES ('Wirehaired Pointing Griffon');
INSERT INTO Breed VALUES ('Wirehaired Vizsla');
INSERT INTO Breed VALUES ('Xoloitzcuintli');
INSERT INTO Breed VALUES ('Yorkipoo');
INSERT INTO Breed VALUES ('Yorkshire Terrier');

# BelongTo
INSERT INTO BelongTo VALUES (1, 'Alaskan Husky');
INSERT INTO BelongTo VALUES (2, 'Australian Shepherd');
INSERT INTO BelongTo VALUES (3, 'Chihuahua');

# Expense
INSERT INTO Expense VALUES (1, '2016-01-13', 74, 'Petco', 'Purina Pro Plan Focus Adult Sensitive Skin & Stomach Salmon & Rice Formula Dry Dog Food');
INSERT INTO Expense VALUES (1, '2016-01-28', 105, 'Dr Smith', 'medicine');
INSERT INTO Expense VALUES (2, '2016-08-26', 144, 'Dr Hudson', 'Exploratory celiotomy - ventral midline ');

# Adopter
INSERT INTO Adopter VALUES ('adopter1@123.com','Susan', 'Callaro', '7628 7-street', 'Greensboro', 'NJ', '04569', '8888888888');
INSERT INTO Adopter VALUES ('adopter2@123.com','Frank', 'Delasancha', '2862 12-street', 'Newark', 'TX', '66783', '6666666666');

# AdoptionApplication
Insert into AdoptionApplication (application_num,date,co_applicant_first_name,co_applicant_last_name,adopter,status) 
Values
 (1, '2016-08-01', 'Cathy', 'Comnick', 'coadopter1@123.com','approved'),
 (2, '2019-06-10', 'Helen', 'Mcrae', 'coadopter2@123.com','pending approval'),


# Adoption
INSERT INTO Adoption VALUES (1, 1, 0, '2016-08-16');


